### ISSUE TITLE
New package name regex for Redhat is breaking YUM 

### ISSUE THREAD

**Issue by nick-george** [elastic/puppet-logstash#353] opened 2017-12-03 21:33 UTC
Hi there, 

I've been having trouble running the latest release of this module on RHEL boxes. I locally mirror the Elastic repository and am serving it out with Apache HTTPD. 

I checked the code and can see that you've modified any RedHat flavoured RPM name to replace '-' with '~'. See https://github.com/elastic/puppet-logstash/blob/master/manifests/package.pp#L42.  And commit https://github.com/elastic/puppet-logstash/commit/05425731abdb4fef70cdfdaeebfdb5f733b238c2

Can I ask why this change was made? The official Elastic RPM releases don't appear to have ~ anywhere in their package names. Is this a feature of YUM that I'm unaware of? 

Cheers, 
Nick

**Comment by jarpy** [comment] 2017-12-05 03:24
Hi Nick,

Would you be able to share a manifest that reproduces the problem for you? This simple one works for me on CentOS 7:

``` puppet
class { 'elastic_stack::repo':
  version => 6,
}

class { 'logstash':
  manage_repo => true,
  version     => '6.0.0',
}
```

We also include both CentOS 6 and CentOS 7 [in the acceptance tests](https://travis-ci.org/elastic/puppet-logstash/builds/311149308), so we can have reasonable confidence that RHEL should work.

The tilde character is used in prerelease versions of Elastic products. I'm not sure if that's a common pattern with YUM. If we use this manifest to set up the special prerelease repository:

```puppet
class { 'elastic_stack::repo':
  version    => 6,
  prerelease => true,
}
```

...then we see the tilde in the available version strings:

```
[vagrant@localhost manifests]$ yum info logstash
Loaded plugins: fastestmirror
elastic                                                  | 1.3 kB     00:00
elastic/primary                                            |  29 kB   00:00
Determining fastest mirrors
 * base: mirror.checkdomain.de
 * extras: mirror.daniel-jost.net
 * updates: mirror.softaculous.com
elastic                                                                   79/79
Available Packages
Name        : logstash
Arch        : noarch
Epoch       : 1
Version     : 6.0.0~rc2
Release     : 1
Size        : 109 M
Repo        : elastic
Summary     : An extensible logging pipeline
URL         : http://www.elasticsearch.org/overview/logstash/
License     : ASL 2.0
Description : An extensible logging pipeline
```

**Comment by nick-george** [comment] 2017-12-05 03:44
Thanks for your response Toby, 
Here's a bit of code that fails for me. 
```
node default {
 class { '::logstash':
   version => '5.6.2-1.noarch'
 }
}
```
I have tried dropping the '-1.noarch' and that is working. It should be good enough for me to get by, but if possible I prefer to specify the exact version and release of packages. 

What if someone wants to install a specific release (e.g -3) of this package? The forced replacing of - with ~ will break their request (as it has done for me). 

As an alternative approach, if you were to drop "regsubst" call in package.pp and someone wanted a tilde in their version string, can't they just add it themselves? E.g 6.0.0~rc2?

Thanks!
Nick

**Comment by jarpy** [comment] 2017-12-05 03:47
Awesome, thanks. Thanks especially for explaining the use case. I added that hack to make RC builds easy to use, without considering that people might do what you're doing.

We can definitely do something nicer. Cheers.

**Comment by nick-george** [comment] 2017-12-05 03:57
Much appreciated 👍

**Comment by jarpy** [comment] 2017-12-05 04:44
Should be fixed in 6.0.1. Please let me know how you go.

https://forge.puppet.com/elasticlogstash/6.0.1/readme

**Comment by nick-george** [comment] 2017-12-16 21:54
Sorry for the late reply on this Toby, it's confirmed working for me.

Thanks for the fix!!

**Comment by jarpy** [comment] 2017-12-18 03:42
Great! Thanks for reporting in.

**Closed** 2017-12-18 03:43 UTC
Labels: bug
