### ISSUE TITLE
doesn't seem to work with puppet-server

### ISSUE THREAD

**Issue by mfournier** [elastic/puppet-logstash#193] opened 2014-11-21 14:36 UTC
Using the logstash module fails with this error when using puppet-server 0.4.0 with puppet 3.7.3:

```
2014-11-21 14:46:36,440 ERROR [puppet-server] Puppet Could not autoload puppet/type/file_concat: uninitialized constant Puppet::Type::File::Owner on node logstash-infra0.infra.internal
org/jruby/RubyModule.java:2723:in `const_missing'
/etc/puppet/environments/marc3/modules/file_concat/lib/puppet/type/file_concat.rb:51:in `(root)'
org/jruby/RubyModule.java:2337:in `module_eval'
/usr/lib/ruby/vendor_ruby/puppet/util/classgen.rb:136:in `genthing'
/usr/lib/ruby/vendor_ruby/puppet/util/classgen.rb:36:in `genclass'
/usr/lib/ruby/vendor_ruby/puppet/metatype/manager.rb:94:in `newtype'
/etc/puppet/environments/marc3/modules/file_concat/lib/puppet/type/file_concat.rb:8:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
/usr/lib/ruby/vendor_ruby/puppet/util/autoload.rb:1:in `(root)'
/usr/lib/ruby/vendor_ruby/puppet/util/autoload.rb:62:in `load_file'
/usr/lib/ruby/vendor_ruby/puppet/util/autoload.rb:199:in `load'
/usr/lib/ruby/vendor_ruby/puppet/metatype/manager.rb:163:in `type'
/usr/lib/ruby/vendor_ruby/puppet/parser/scope.rb:803:in `find_builtin_resource_type'
/usr/lib/ruby/vendor_ruby/puppet/parser/scope.rb:799:in `find_resource_type'
/usr/lib/ruby/vendor_ruby/puppet/parser/scope.rb:839:in `resolve_type_and_titles'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:37:in `evaluate'
[...]
```

I'm currently working around this issue by replacing electrical/puppet-lib-file_concat by puppetlabs/puppetlabs-concat. The change is trivial:

```
diff --git manifests/config.pp manifests/config.pp
index c224e47..97b9d34 100644
--- manifests/config.pp
+++ manifests/config.pp
@@ -52,10 +52,8 @@ class logstash::config {
       require => File[$logstash::configdir]
     }
 
-    file_concat { 'ls-config':
+    concat { "${logstash::configdir}/conf.d/logstash.conf":
       ensure  => 'present',
-      tag     => "LS_CONFIG_${::fqdn}",
-      path    => "${logstash::configdir}/conf.d/logstash.conf",
       owner   => $logstash::logstash_user,
       group   => $logstash::logstash_group,
       mode    => '0644',
diff --git manifests/configfile.pp manifests/configfile.pp
index dab7932..e8d0391 100644
--- manifests/configfile.pp
+++ manifests/configfile.pp
@@ -37,12 +37,11 @@ define logstash::configfile(
   $order = 10
 ) {
 
-  file_fragment { $name:
-    tag     => "LS_CONFIG_${::fqdn}",
+  concat::fragment { $name:
+    target  => "${logstash::configdir}/conf.d/logstash.conf",
     content => $content,
     source  => $source,
     order   => $order,
-    before  => [ File_concat['ls-config'] ]
   }
 
 }
```

Would you consider replacing or making the file concatenation backend configurable ?

Thanks !

**Comment by malnick** [comment] 2015-02-12 21:17
I hit this issue today as well.

**Comment by malnick** [comment] 2015-02-13 00:04
Also digging into why it's using a package resource to download the logstash package on ubuntu:

```
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install logstash' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package logstash
Error: /Stage[main]/Logstash::Package/Logstash::Package::Install[logstash]/Package[logstash]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install logstash' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package logstash
```

Nowhere is there any package resource for this, so I'm really lost as to why this is trying to use apt instead of the wget as specified in the params. 

In running on 3.7.4, ubuntu 12LTS

**Comment by azhurbilo** [comment] 2015-07-23 04:58
+1

**Comment by cdenneen** [comment] 2015-08-14 21:42
+1

**Comment by tuxtek** [comment] 2015-08-19 20:21
+1

**Comment by cdenneen** [comment] 2015-08-19 21:32
@electrical this patch does fix issue as long as file_concat is removed from PM (so removed when pluginsync runs).
Would you merge this and update the dependency from file_concat to puppetlabs/concat?

**Comment by electrical** [comment] 2015-08-20 08:15
Hi,

The main issue that it doesn't work with PuppetServer is that i moved the file_concat library into an other name space which has all the fixes. The new location is https://forge.puppetlabs.com/electrical/file_concat
That said, i'm not planning to move to pl-concat any time soon for reasons i've explained several times.
Also pl-concat will be moving to use my library in the newest version ( work in progress )

Also I'm planning with the new version of the module to drop the concat part all together since LS reads separate files anyway.


@malnick your issue is most likely about not enabling the repository. there are 2 options to enable the repo and set the major version number for it.

**Comment by cdenneen** [comment] 2015-08-20 18:05
@electrical I know this is a sore subject with a lot of people but one of the major issues in the OSS community is the fact that there are so many different versions/forks/etc of the same thing. It's confusing on what should be a standard, the "default", etc. With the model of puppet "approved" and puppet "supported" modules it is to help reduce this confusion and complexity (similar to the puppet community group starting to import widely used modules into a common name space https://github.com/puppet-community). You could say it is similar to @jordansissel rant on "there are enough date format's out there... stop inventing new ones". If the pl-concat module is an already PE supported module then wouldn't it make sense to move to that one? Sorry I haven't seen your explanations before. 

You mentioned pl-concat will be moving to use your library but I can't seem to find that. Only reference I've found is the removal of file_concat dependency from the .fixures.yml?

I'll undo the patch from this PR and test with latest file_concat as I guess that is the recommended approach?

**Comment by jordansissel** [comment] 2015-08-20 19:18
@cdenneen last I heard PL was working on merging in @electrical's file_concat stuff into the main file concat thing, but I don't know the status.

**Comment by cdenneen** [comment] 2015-08-20 19:51
@jordansissel thanks... yeah I was looking through the master, 2.0.0, 2.0.x branches and didn't see anything yet

**Comment by electrical** [comment] 2015-08-21 08:23
@cdenneen they had to revert the 2.x releases because of a bug they hit in Puppet.
I'm working with their team to get things solved so they can do an other attempt on doing a release with the faster library. See https://groups.google.com/forum/#!searchin/puppet-users/concat/puppet-users/4_Sxrfl4uUY/okhVoFrrTogJ for details.

**Comment by cdenneen** [comment] 2015-08-26 18:01
@electrical 
So tested this with:
```
/modules
└─┬ elasticsearch-logstash (v0.5.1)
  ├── ispavailability-file_concat (v0.3.0)
  └── puppetlabs-stdlib (v4.1.0)
```
and following result:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/file_concat: Could not autoload puppet/provider/file_concat/windows: no such file to load -- puppet/provider/file_concat on node lsindexer.vm.local
```

So it appears this is still happening with latest 0.3.0 of file_concat

**Comment by cdenneen** [comment] 2015-08-26 18:05
@electrical whoops... i allowed the metadata.json of logstash to install 0.3.0 again instead of 1.0.1 from electrical-file_concat I've updated and appears to be working :+1:

**Comment by caskolkm** [comment] 2016-03-24 16:29
Any fix or progress on this?

**Comment by cdenneen** [comment] 2016-03-24 20:53
use electrical/file_concat and it will work

**Comment by caskolkm** [comment] 2016-03-25 09:09
@cdenneen thnx, although is still nicer to replace it with puppetlabs/concat

**Comment by caskolkm** [comment] 2016-03-29 11:14
@cdenneen still got the following error: 

`Error: /Stage[main]/Logstash::Config/File_concat[ls-config]: Failed to generate additional resources using 'eval_generate': Could not intern from application/octet-stream: No format match the given format name or mime-type (application/octet-stream)`

**Comment by cdenneen** [comment] 2016-03-30 00:57
Puppet version?
Module version used of file_concat?
Module version of logstash?

**Comment by jarpy** [comment] 2016-05-04 07:21
The current version looks to be OK with puppetserver.

**Closed by jarpy** 2016-05-04 07:21 UTC

**Comment by iwalz** [comment] 2016-09-27 10:45
Same here.
Puppet version: 4.5.3
Logstash version: 0.6.4
file_concat version: 1.0.1

I can confirm that using 0.3.0 works and 1.0.1 not. 
This module forced us to import yet-another-concat-module into our internal repository, which means we have to maintain upgrades and such on our own + the fact, that the latest release version doesn't work well with puppet server feels really bad for enterprises ... Which should somehow be the target group for this module!

**Comment by jeffgage** [comment] 2016-12-02 20:10
Hint: I hit this bug when I had unescaped double quotes inside a filter definition.

**Comment by wscheele** [comment] 2016-12-13 22:41
@caskolkm I got that exact same error while connecting from a 3.8.7 agent to a 2.7.2 puppetserver. I managed to workaround the problem with the hack described as a comment in:
https://tickets.puppetlabs.com/browse/MODULES-3310

**Comment by jarpy** [comment] 2016-12-13 22:49
Hi all. The upcoming release for Logstash 5 drops concat completely, so if you are able to upgrade to Logstash 5, then hopefully this issue will go away for you.
