### ISSUE TITLE
ensure => absent fails when run twice

### ISSUE THREAD

**Issue by exi** [elastic/puppet-logstash#228] opened 2015-07-01 14:47 UTC
The first run with ensure => absent successfully removes the existing init script.
The second run fails because it instantiates the puppet service which fails because the init file is missing:

```
Error: /Stage[main]/Logstash::Service/Logstash::Service::Init[logstash]/Service[logstash]: Could not evaluate: Could not find init script for 'logstash'
```

**Comment by electrical** [comment] 2015-07-01 15:01
Hi,

This issue has been solved by the ES puppet module but needs to be ported to the LS module.
We are planning to do this when the ES puppet module is at version 1.0 so we can port over all the nice fixes to the LS module.

**Comment by exi** [comment] 2015-07-01 15:03
Do you roughly know when this will happen? I think until then it should at least be documented that using ensure => absent will break your puppet setup and should currently not be used.

**Comment by electrical** [comment] 2015-07-01 15:05
I'm afraid i don't have an ETA yet. There are several key features that are still in the making.

**Comment by exi** [comment] 2015-07-01 15:12
Would you accept a pull request updating the comments and documentation to make clear that ensure => absent is not supported right now?

**Comment by electrical** [comment] 2015-07-01 15:15
Yes of course :-)

**Comment by exi** [comment] 2015-07-01 15:30
what about removing the ensure => absent case altogether?

**Comment by exi** [comment] 2015-07-01 15:31
or to be precise, the whole 'ensure' option

**Comment by electrical** [comment] 2015-07-01 15:33
Well, running it once does work right?

**Comment by exi** [comment] 2015-07-01 15:58
@electrical i just implemented a quick workaround that leads to the desired behavior and fixes the bug

**Comment by exi** [comment] 2015-07-11 12:01
@electrical what would it take to merge my pull request?

**Comment by jarpy** [comment] 2016-05-06 06:24
I added an [acceptance for this](https://github.com/elastic/puppet-logstash/blob/deb25876b9ed49cb25ff259d5ccda93aabf9974e/spec/acceptance/class_logstash_spec.rb#L85) under the new test framework, but it [doesn't want to fail](https://travis-ci.org/elastic/puppet-logstash/builds/128196320).

Either I'm missing something in my test (_failure is always an option_), or this issue has been fixed by stealth.

Is the problem still manifesting (no pun intended) for you in `master`/`0.6.0`? If so, I'd be very grateful if you could help me reproduce it correctly.

Thanks.

**Comment by jarpy** [comment] 2016-05-17 00:25
Closing this issue since it _appears_ to be resolved.

**Closed by jarpy** 2016-05-17 00:25 UTC
Labels: in progress
