### ISSUE TITLE
Logstash 5.x Support

### ISSUE THREAD

**Issue by Cova** [elastic/puppet-logstash#312] opened 2016-10-31 17:10 UTC
There's an issue tracking the outstanding issues for ElasticSearch 5.x support from its puppet module, so I figured Logstash should have one too.

**Comment by vchan2002** [comment] 2016-11-02 22:20
So, I just messed around by hardcoding the rpm file as the package_url parameter as 
https://artifacts.elastic.co/downloads/logstash/logstash-5.0.0.rpm on an Amazon Linux server.

The RPM installed correctly without any issues, so there's that....

Here's what I found so far.

a.  java.pp would probabaly need to be updated as Logstash 5 only supports Java 8.
b.  params.pp will need to be set to support the new pathing for logstash.  (/opt/logstash then vs /usr/share/logstash now)
c.  it did not lay down the init.d file for some reason.
d.  Needs a new mechanism to lay down the logstash.yml file that is new for Logstash 5.....

Will post more as I research more...

**Comment by jarpy** [comment] 2016-11-03 03:38
Thanks for the research @vchan2002. Let me respond to a few of those points so that everyone knows the plan.

`java.pp` should really be _removed_. The Logstash module has no business managing the system java install. That's what `puppetlabs/java` is for! :)

The init system needs to be completely removed/rewritten. Logstash 5 introduces more native support for various init systems, with `systemd` being particularly relevant. The module should no longer provide SysV init scripts on Logstash's behalf, especially on systems that don't actually SysV init (most modern distros don't). More info here: https://www.elastic.co/guide/en/logstash/5.0/running-logstash.html

Obviously, these are big changes to how the module works and they won't be backward compatible. I've created a new "5.x" branch where the heavy hacking can take place. When ready, I'll release that branch on the Forge as a new major version that specifically supports Logstash v5 (only).

**Comment by vchan2002** [comment] 2016-11-03 15:57
@jarpy Thanks for the feedback....

I believe that you suggested that, over at the elasticsearch puppet repo, that we should consider completely splitting the ES 5 puppet module to its own given the number of potential breaking changes for ES 5.
Given that, from what I've seen so far, and that I've deep diving into what exactly the existing module does, there's probably a lot more breaking changes between logstash 2.x and logstash 5.x that we should also consider doing the same.  

In the meanwhile, I'll pull the repo down and hack away at the 5.0 branch.

**Comment by elisiano** [comment] 2016-11-03 18:23
CentOS 6.X will be supported until 2020. that's more than 4 full years. Removing that support will make *many* users frown as not everybody has the possibility to upgrade to the latest OS.

**Comment by vchan2002** [comment] 2016-11-03 19:01
Hi @elisiano,

I did initially share your concern in regards to CentOS 6 also, as Amazon Linux, being the Frankenstein OS that it is, does not support systemd either. 

From what I see from that article about Logstash 5, however ,the rpm actually lays down an upstart file at /etc/init/logstash.conf; it sure did on my Amazon Linux instance; i'd imagine CentOS 6 does that also.  The current logstash module actually goes out of the way to remove that file and insists on laying down its own init.d file if the service provider is set as init.

Given that, I would think that if we just let the rpm do its thing, we should be OK... I think there will need to do some additional work in making sure that we tell the module which is the right service provider, depending on the OS.

**Comment by elisiano** [comment] 2016-11-03 19:06
if that's the case it should work. I just think that having puppet manage the init.d file is a more solid solution instead of relying on the RPM package. 

But as long as it works and CentOS 6.X is a supported platform, I'm not too concerned about it.

**Comment by jarpy** [comment] 2016-11-07 05:45
Absolutely. CentOS 6.X is a supported operating system for Logstash 5.0, so this module needs to support it too. The good news is that providing support like that in the module now actually means a whole lot less effort, because Logstash itself knows a lot more about different distros and their init systems. 🎉

If we have to provide explicit init support in the module for a supported OS, then that's a bug in Logstash, and we can get it fixed upstream.

**Comment by jarpy** [comment] 2016-11-07 06:44
I pushed a bunch of changes to the 5.X branch and things are starting to come together. Some of the more noteworthy changes include:

- Removed all logic around the installation of the Java runtime. This module should not be messing around with your Java install, and should not mandate the puppet code (or otherwise) that your site uses to get Java installed. If this change surprises you, and you have a few minutes, then @glarizza [can explain it](https://www.youtube.com/watch?v=v9LB-NX4_KQ&feature=youtu.be&t=44m57s) better than I ever could.

- Removed all of the init scripts logic in favour of native support from the Logstash packages, as we talked about above.

- Replaced the init defaults template with one for Logstash's new `startup.options` feature.

Less notable changes abound. I'm taking full advantage of the major version change to reduce and refactor the code base. This module got so crufty, that working on it was making me a sad panda.

Finally, I created a GitHub [project](https://github.com/elastic/puppet-logstash/projects/1) in an attempt to track some of the changes needed for 5.x as well as some of the major refractors that I'd like to include in the release. Suggestions warmly welcomed, naturally!

**Comment by jarro2783** [comment] 2016-11-16 04:41
I'm trying out the 5.x branch and discovered that in logstash::params, $installpath should be set to `/usr/share/logstash`, otherwise it seems good.

**Comment by siliconalchemy** [comment] 2016-11-22 13:36
Thanks for your work on this.  Initially seems good.  One thing I've come across is that logstash is being run with '-Xmx500m -Xss2048k' by default and I can't see where this is set.  Previously I set this in LS_HEAP in init_defaults but init_defaults doesn't exist in new branch.   So I'm setting:
```
        startup_options => {
		    'LS_JAVA_OPTS'        => '"-Xmx350M -Xms350M"',
		},
```
This writes the value into /etc/logstash/startup.options but isn't read at start.

**Comment by elisiano** [comment] 2016-11-22 15:40
Does this branch keep backwards compatibility with 2.x?
Since in my environment I have mostly 2.x, I wouldn't want to risk breaking anything while testing 5.x.

**Comment by elisiano** [comment] 2016-11-23 16:16
I found out the hard way that this is not backwards compatible.
Removing `logstash::init_defaults` break previous installations.
If I move to `logstash::startup_options` will logstash `2.x` be supported?

**Comment by jarpy** [comment] 2016-11-23 22:08
Hi @elisiano. The short is answer in "no", sorry.

The plan is to continue with development as a true major version release, with changes that are not backward-compatible. As you've discovered, the init system handling, in particular, is very different because it is very different in Logstash itself.

Earlier versions of this module were severely limited (broken, really) on systemd distributions, because Logstash 2 provided only SysV init support, which was then badly handled by Puppet. Logstash 5 provides native systemd units, which fixes all the pain associated with service management under Puppet. See: #302, #300, #286, #266. This is pretty crucial now that there are so few distros left running SysV init.

On top of that, the code-base for the version 2 module is just seriously out of hand, with dead logic, needlessly complex conditional processing, and gross violation of separation-of-concerns (it has code to install Java!). This is the best chance we have to aggressively refactor the module into something more maintainable and more in line with accepted good practice.

**Comment by jarpy** [comment] 2016-11-23 22:12
Thanks for the report, @siliconalchemy. I added a task on the project board to write a test for this case.

https://github.com/elastic/puppet-logstash/projects/1#card-897051

**Comment by jarpy** [comment] 2016-11-23 22:15
Thanks @jarro2783, `$installpath` ended up being dead code, so I ripped it out. Good riddance! :D

https://github.com/elastic/puppet-logstash/commit/e2b04305a46d8edcf33b3dacb4fb86df2a88fb4a

**Comment by elisiano** [comment] 2016-11-23 22:34
@jarpy I understand the need to move forward but dropping support for current installations doesn't feel like the right approach. If the two modules are not compatible then they should be named differently. 

I'm pretty sure I'm not the only one who has to keep supporting dated installations. 
Also, if there's no simple way to have parallel installations it might slow down the overall adoption.

**Comment by jarpy** [comment] 2016-11-23 22:59
Do you use Puppet environments? They are a solid way to maintain different module versions without resorting to namespacing tricks.

https://github.com/elastic/puppet-logstash/issues/297

**Comment by jarpy** [comment] 2016-11-24 23:26
Acceptance tests are now passing for a bunch of platforms:

https://travis-ci.org/elastic/puppet-logstash/builds/178502198

The situation is actually better than it looks in that build. Most of the failures are problems with the test environment. The unusual challenges of running a full-scale init process inside a container are hitting us here. I think that for the Upstart distributions (Centos 6, Ubuntu 12.04), the Upstart system is not sufficiently  convincing to be detected by [Pleaserun](https://github.com/jordansissel/pleaserun), which creates the appropriate init config depending on the detected init system.

I'm working now on improving the containers to more "Upstart-ey".

**Comment by jarpy** [comment] 2016-11-25 00:58
Fixed Upstart for the Ubuntu 12.04 container in 6579eaa190444fa26003d9987a7ef6b5a4154b23.

Much better: https://travis-ci.org/elastic/puppet-logstash/jobs/178735169

**Comment by Krixa** [comment] 2016-11-26 17:01
It would be nice to be able to override the service_provider, since Puppet defaults to SysV on rhel6 and it fails to start.

**Comment by jarpy** [comment] 2016-12-01 03:07
@Krixa good idea. Which version of Puppet are you using by the way? I've found init system detection to be kinda variable across versions.

**Comment by Krixa** [comment] 2016-12-01 08:00
PE 3.8.7

**Comment by elisiano** [comment] 2016-12-01 15:09
I'm in a similar situation as @siliconalchemy .
I'm not sure this is something that has to do with the puppet module (as opposed to the packaged files) but `/etc/logstash/startup.options` seem to be ignored (specifically `LS_JAVA_OPTS`).
I see that whenever that file is changed `./bin/system-install` is executed but effectively the changes are ignored.

How I solved this for now is 
  * add `EnvironmentFile=-/etc/logstash/startup.options` to `/etc/systemd/system/logstash.service`
  * `systemctl daemon-reload`
  * `systemctl restart logstash.service`

This obviously is not a long-term solution because as soon as I upgraded the package the changes were lost (and puppet does not manage the systemd service file).

Is this something that the upstream package should fix (either modify `system-install` to take into account all variables or include the additional environment file in `logstash.service`)?

**Comment by siliconalchemy** [comment] 2016-12-01 15:13
@elisiano - looks like java options are now set in /etc/logstash/jvm.options.

**Comment by elisiano** [comment] 2016-12-01 15:15
thanks @siliconalchemy .
I can't keep up with all these changes!! All I did was upgrade from logstash 5.0.1 to 5.0.2 (which semantically should not have introduced big changes).

Anyhow, I'll see if jvm.options works as intended, thanks again.

**Comment by siliconalchemy** [comment] 2016-12-01 15:18
@elisiano - Fun isn't it :)

I don't think the logstash module is currently aware of this file, so make sure you set:
 purge_configdir	=> false,
otherwise the file will be wiped out.  You might need to reinstall the rpm/dpkg to get it back.

**Comment by elisiano** [comment] 2016-12-01 15:47
So yes, `jvm.options` works although the environment variable `$LS_JAVA_OPTS` [should still be supported](https://github.com/elastic/logstash/blob/master/bin/logstash.lib.sh#L67-L84)

**Comment by jarpy** [comment] 2016-12-05 06:13
Hi all. Support for `jvm.options` is now in the `5.x` branch.

https://github.com/elastic/puppet-logstash/commit/05a3c2c2c613b4f2e3a0e73b55e567ff157c1d29

**Comment by jarpy** [comment] 2016-12-06 05:30
Hi @Krixa, explicit override for the service provider (init system) is now supported.

https://github.com/elastic/puppet-logstash/commit/568efac50c4482e2ee8a2af9f9492d985e644317

**Comment by jarpy** [comment] 2016-12-06 05:31
Oh, and the module should default to Upstart on RHEL6 now too.

https://github.com/elastic/puppet-logstash/commit/35e6d67d011abc6440465b3053156f4d377654f6

**Comment by Krixa** [comment] 2016-12-06 07:33
Nice!

**Comment by Cosaquee** [comment] 2016-12-06 11:18
@jarpy thanks for your work ! Any info about planed release of new version with 5.x support ?

**Comment by jarpy** [comment] 2016-12-06 23:11
Your welcome, @Cosaquee, I just wish I was going faster!

I can't give you a date, sorry, but it's looking pretty good now, with the [existing acceptance tests passing](https://travis-ci.org/elastic/puppet-logstash/builds/181562438) on all platforms. If you have the time and an appropriate test environment to try out the `5.x` branch, now is the very best time to offer feedback. Until we call it "released", we have the luxury of being able to change things quite aggressively, including the API of the module itself, where that makes sense.

Today, I'm working on removing the unneeded "file_concat" logic, which will reduce complexity and fix compatibility problems with puppet-server.

**Comment by jarpy** [comment] 2016-12-07 00:57
All the `file_concat` stuff is gone now. The module now creates one file per `logstash::configfile` declaration.

https://github.com/elastic/puppet-logstash/commit/054248c7d4b38a74fb131ea72d37fe0c2637e1ad

Note: This patch also removes the needless (IMO) abstraction of templating from `logstash::configfile`, so if you were doing:

```
logstash::configfile { 'logs':
  template => 'path/to/template'
}
```
Now you should do:
```
logstash::configfile { 'logs':
  content => template('path/to/template')
}
```
That's consistent with normal templating for file resources, and doesn't add abstraction magic over something that Puppet coders already do every day.

**Comment by elisiano** [comment] 2016-12-07 03:24
@jarpy the templating abstraction was not needless at all. On the contrary I found it pretty valuable in conjunction with create_resources and hiera. 

```
create_resources('logstash::configfile', hiera('ls_configfiles', {}))
```

won't this change break that functionality (since functions are not evaluated in hiera)?

**Comment by jarpy** [comment] 2016-12-07 05:15
Ah OK. Thanks for the feedback, @elisiano. Let's put it back then, it's very easy to implement, I just thought it was redundant. Thanks for setting me straight.

**Comment by jarpy** [comment] 2016-12-07 07:36
@elisiano: Explicit template support is now restored, and has proper test coverage.

https://github.com/elastic/puppet-logstash/commit/afbcf927cdceb83f4105b2ad8b7d22a603ca18e1

Thanks again for taking the time to communicate. It really helps me out.

**Comment by elisiano** [comment] 2016-12-07 10:54
Thanks @jarpy

**Comment by Cosaquee** [comment] 2016-12-08 09:55
@jarpy maybe some sort of roadmap of changes that needs to be done before 5.x support would be nice. :) Right now there is no informations what has to be done. With such roadmap, one might want to contribute and help you with 5.x support :D

**Comment by jarpy** [comment] 2016-12-12 02:23
There's [this page](https://github.com/elastic/puppet-logstash/projects/1), @Cosaquee. I'm trying to track most things there. Most tasks there are now in the "Check Docs" state, which is good news. I feel that the module is more or less functionally complete.

If anyone wants to help, the bests things right now are probably:

- Documentation patches.
- "Beta" testing. ie. Try it out and tell me what broken! :)

**Comment by jarpy** [comment] 2016-12-12 02:34
The `logstash.yml` file is now configurable as a hash parameter.

https://github.com/elastic/puppet-logstash/commit/ecc9804478f2ef2d1d085c37ef2e2f0f6b05468c

**Comment by jarpy** [comment] 2016-12-12 02:44
**RFC on `$configdir` and `purge_configdir`:**

Currently, setting `purge_configdir` causes everything to be deleted from `/etc/logstash/`, which seems weird to me. I can understand wanting to purge the pipeline config directory at `/etc/logstash/conf.d/`, to ensure there are no orphaned pipeline config fragments, but deleting the settings files in `/etc/logstash/` looks like a bug to my eyes.

Does anyone have a use-case where they particularly want to delete `/etc/logstash/*`, rather than `/etc/logstash/conf.d/*`? If not, I will modify `purge_configdir` to do the latter.

**Comment by elisiano** [comment] 2016-12-12 15:33
How about patternfiles? I would consider them part of the configuration.

**Comment by jarro2783** [comment] 2016-12-13 00:31
It seems sensible to me to not purge `/etc/logstash`. I spent a while working out why logstash wasn't starting due to `log4j2.properties` being missing.

**Comment by jarpy** [comment] 2016-12-13 05:57
Thanks, folks. Perhaps it's best then to (optionally) purge pipeline config and patterns, but leave settings files alone. 👍 

I just pushed a large refactor of the docs, including porting everything to puppet-strings format. Barring the change above, I think the module is now feature-complete and ready for some serious exploratory testing before official release.

**Comment by jarpy** [comment] 2016-12-14 04:17
We now purge patterns and pipeline config, but leave settings (`/etc/logstash`) alone.

https://github.com/elastic/puppet-logstash/commit/43ce428874e7ed803d61588c1f15ff3d832e02d8

**Comment by jarpy** [comment] 2016-12-14 04:19
Also added underscores to `auto_upgrade` and `config_dir` params. This will be a breaking change if you use those params. Forgive me, it's our last chance to fix the API until at least Logstash 6!

**Comment by jarpy** [comment] 2016-12-15 03:27
Fun times today:

#### Released the 5.x version to Puppet Forge
Available now at: https://forge.puppet.com/elastic/logstash

Note: The forge name is `elastic/logstash` not `elasticsearch/logstash`. The renaming goes with the company, which also renamed itself, and protects anyone who may be tracking the latest version of `elasticsearch/logstash` from pulling the new, non-backwards compatible version without making a deliberate choice.

#### Preserved the source for the old version in a new 2.X branch here on GitHub.
This will enable critical fixes to be applied to the old module if something really important comes along.

#### Merged the 5.X branch into master
The master branch now reflects the head of development in the new 5.x era.

Note: If you are tracking the master branch then you will get the new, non-backward compatible version when you pull or update submodules. Hopefully, people who are managing their Puppet models with Git, rather than the Forge, have the moves to handle this.

**Closed** 2016-12-19 05:15 UTC
