### ISSUE TITLE
CentOS7 and puppet 4 service start issue

### ISSUE THREAD

**Issue by jjuarez** [elastic/puppet-logstash#344] opened 2017-06-05 18:16 UTC
Apparently in CentOS 7 platforms executing puppet version 4.9 (agent 1.9.3) there are some issues during the service start up, and you have to force the parameter logstash::service_provider to 'systemd'

**Comment by jarpy** [comment] 2017-06-06 04:30
Hi,

I'm afraid I can't reproduce this:

```
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

$ puppet --version
4.9.4

$ cat > test.pp <<EOF
> include logstash
> logstash::configfile { 'basic_config':
>   content => 'input { tcp { port => 2000 } } output { null {} }'
> }
> EOF

$ sudo puppet apply test.pp
[snip]
Notice: /Stage[main]/Logstash::Service/Service[logstash]/ensure: ensure changed 'stopped' to 'running'
Notice: Applied catalog in 61.79 seconds

$ systemctl status logstash
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-06-06 04:28:31 UTC; 21s ago
 Main PID: 4613 (java)
   CGroup: /system.slice/logstash.service
           └─4613 /usr/bin/java -Dfile.encoding=UTF-8 -Djava.awt.headless=true -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCMSInitiatingOccupancyOnly -X...
```

The [tests don't reproduce it either](https://travis-ci.org/elastic/puppet-logstash/jobs/239811096).

Is there anything else you can share about how to reproduce the error?

Thanks.

**Comment by jarpy** [comment] 2017-06-14 23:34
Closing. If anyone is able to reproduce this, please reopen the issue and we'll fix it together. Thanks.

**Closed by jarpy** 2017-06-14 23:35 UTC

**Comment by yupvr** [comment] 2017-10-10 10:41
Hi!
I have the same issue:
```
CentOS Linux release 7.4.1708 (Core)
puppet --version 5.3.2
elastic-logstash (v5.3.0)

```
Manifest:
```
  include logstash
  logstash::configfile { 'basic_config':
    content => 'input { tcp { port => 2000 } } output { null {} }'
  }
```
```
# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for elastic.local
Info: Applying configuration version '1507631975'
Error: Systemd start for logstash failed!
journalctl log for logstash:
-- No entries --

Error: /Stage[main]/Logstash::Service/Service[logstash]/ensure: change from 'stopped' to 'running' failed: Systemd start for logstash failed!
journalctl log for logstash:
-- No entries --
```
```
# systemctl status logstash
Unit logstash.service could not be found.
```
